name = "socialcal"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-22"

[[d1_databases]]
binding = "DB"
database_name = "socialcal"
database_id = "e1f1259a-3e37-4ec8-9cc5-7610814219f7"
migrations_dir = "migrations"
